### ISSUE TITLE
Document how do we pass in and reference options in plugins

### ISSUE THREAD

**Issue by amasad** [thejameskyle/babel-plugin-handbook#18]

**Comment by zpao** [comment]
I agree that this would be helpful. I'm converting a plugin that took advantage of the `_underscoreOption` pattern then read from `state.opts._underscoreOption`. http://babeljs.io/docs/plugins/#options indicates that you can just pass in options in with the plugin itself, then read from `state.opts.<whatever>` (based on the referenced plugin in the docs - https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-async-to-module-method/src/index.js#L13).

I'm assuming state.opts is specific to each plugin so that options can't clash but that's not clear and I'd like to know that more fully before making my option names more generic.

**Comment by thejameskyle** [comment]
Right I forgot to do this.

```js
{
  "plugins": [
    ["my-plugin", { "opt1": "value", "opt2": "value" }]
  ]
}
```
```js
export default function({ types: t }) {
  return {
    visitor: {
      Node(path, state) {
        state.opts;
        // { opt1: 'value', opt2: 'value' }
      }
    }
  };
}
```
