### ISSUE TITLE
How to identify whether a variable is declared previously or not?

### ISSUE THREAD

**Issue by udnisap** [thejameskyle/babel-plugin-handbook#28]
Given a variable name and a score can we check whether a variable is defined in the scope or not?
will `path.scope.hasBinding(path.node.name)` works all the time?
This also returns methods that are built into javascript such as `forEach`. Any ideas?

**Comment by udnisap** [comment]
I ended up writing https://www.npmjs.com/package/babel-plugin-modularize
which does what I wanted to.

**Comment by thejameskyle** [comment]
Sorry I meant to get back to this. `scope.hasOwnBinding` is likely what you were looking for.

---

On a another note– and I don't like saying this because it's very discouraging– but that plugin is not a healthy idea. You're adding behavior to the language which will make your life harder. It is far better to have static references and errors on undeclared references and not implicit behavior based on the naming of undeclared references.

I would actively encourage you to take down that plugin. It's going to cause anyone who uses it trouble. It's nice that you got the opportunity to play around with Babel plugins though.

**Comment by udnisap** [comment]
@thejameskyle thanks for the heads up. I was actually looking for a way to migrate the code not to use it part of the build process. I have a legacy code with global referenced objects. With this plugin I can make it localized. This will be used in the code migration process not in the building process. 

I understand this will cause further problems and developers will have no idea when their code is transpield into this if they have it in their build process. I will add a disclaimer ontop.
